name: Test and Score

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest --maxfail=5 --disable-warnings --tb=short > result.log || true
        cat result.log

    - name: Count passed tests
      id: count
      run: |
        PASSED=$(grep -oP '(\d+) passed' result.log | grep -oP '\d+')
        echo "::set-output name=passed::$PASSED"

    - name: Show score
      run: |
        SCORE=$(( ${{ steps.count.outputs.passed }} * 1 ))
        echo "Your score is: $SCORE/5"
        echo "SCORE=$SCORE" >> $GITHUB_ENV

